### PR TITLE
Add chevron data-toggle

### PR DESCRIPTION
**Pull request by nicoleiocana**
Referring to this issue:

https://gitlab.torproject.org/torproject/web/manual/-/issues/33#note_421204

and related to this PR:

https://github.com/torproject/manual/pull/67

This is the css code for the font-awesome chevron icons to function when the topics are collapsed & expanded.

### CODE REVIEW

**Comment by holantonela-zz** [comment]
This is not ok. We should not touch `/static`.

**Comment by nicoleiocana** [comment]
Which stylesheet is appropriate to place this code? Once a specific .css file has been approved, I will update the change, link that stylesheet, then push the new commits.

**Comment by nicoleiocana** [comment]
@holantonela Thanks for the guidance. I realized that the original chevron styling was in the _tor.scss file, so I:
- [x] Reverted the /static folder back to its original code
- [x] Removed open-iconic styling of any chevron class
- [x] Migrated the toggle animation code to _tor.scss

**Comment by holantonela-zz** [comment]
Looks good now, thank you!

**Comment by nicoleiocana** [comment]
Merged here: https://gitlab.torproject.org/torproject/web/lego/-/commit/5b8cf5ae67293c4fa494abeb42e99821eb32543d

**Pull request closed without merging**
